### ISSUE TITLE
convert our project to web

### ISSUE THREAD

**Issue by nikitadizhur** [TechnionYP5777/UpAndGo#207]

**Comment by leyaniv** [comment]
So after few hours of trying, I finally managed to add GWT using MAVEN to an existing project. There's a [wiki page](https://github.com/TechnionYP5777/UpAndGo/wiki/GWT---Maven-project) to explain the process that was done. We didn't use the MOJO plugin, instead we used [something simpler](https://tbroyer.github.io/gwt-maven-plugin/index.html#).

Anyone please pull the change and test that nothing was broken. Then in order to test GTW, I think you first need to right click on the project and select **Maven -> Update Project**. Then you can right click again and select **Run As -> GWT Development Mode**. A tab called **Development Mode** should pop up next to **Console**. There will be a link written inside it. Double clicking on it should open a web browser with the message "Hello World" on a blank page. Please comment whether it worked for you or not.

@nikitadizhur 
@OmriBS 
@kobybs 
@danabra

**Comment by nikitadizhur** [comment]
@leyaniv package client and file Webapp.gwt.xml should be inside presenter, rather under the main package (java), because they aren't the part of presenter.

**Comment by leyaniv** [comment]
Well, that's your expertise to know what goes where. I'll refactor this later because I'm done for today and heading to bed.

**Comment by danabra** [comment]
Worked for me
