### ISSUE TITLE
Change Logging Library To Support GWT

### ISSUE THREAD

**Issue by danabra** [TechnionYP5777/UpAndGo#221]
current logging library doesnt support GWT (can log only on server side)

time estimation: 2 hours

**Comment by danabra** [comment]
We are now using gwt-log library - https://github.com/fredsa/gwt-log
in order to log messages do exactly the same thing as before (eclipse should automatically import `import com.allen_sauer.gwt.log.client.Log;` into your class)

**Comment by nikitadizhur** [comment]
@danabra, after the pull request I'm receiving following errors:
![image](https://cloud.githubusercontent.com/assets/20992584/25301238/202f35dc-272a-11e7-931c-e591888e824f.png)
maybe you know how to solve that?

**Comment by danabra** [comment]
@nikitadizhur  I think it has to do with the `.classpath` file, and change the path in the `classpathentry `.
But I see you've commited without compilation errors, so is it ok now?

**Comment by danabra** [comment]
@nikitadizhur @OmriBS I think that the slide on our [logging library](https://github.com/fredsa/gwt-log) needs to be updated for the presentation tomorrow. Note that we still use logback on the server side, the main difference is that now we can log on the client side the same exact way and the logging from the client side are shown in a draggable window in the browser (you can see for yourselves when you run the project in the browser). If you any questions please ask me.

**Comment by nikitadizhur** [comment]
@danabra I still get those errors and I can't build the project. But I guess IDE can make some partial builds for files that don't rely on missing libraries.

**Comment by nikitadizhur** [comment]
@danabra, @OmriBS, as for slide about logging, I think that we won't include it in presentation (Tanya said that there is no need to). We will simply mention it verbally.

**Comment by tanyabrokhman** [comment]
Right. No need to add slide on logging. Pls send me the updated ppt

On Apr 22, 2017 13:05, "Nikita Dizhur" <notifications@github.com> wrote:

@danabra <https://github.com/danabra>, @OmriBS <https://github.com/OmriBS>,
as for slide about logging, I think that we won't include it in
presentation (Tanya said that there is no need to). We will simply mention
it verbally.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/TechnionYP5777/UpAndGo/issues/221#issuecomment-296362642>,
or mute the thread

**Comment by danabra** [comment]
@nikitadizhur can you bring your laptop tomorrow and show me the problem?
