### ISSUE TITLE
Info about event collision is weired

### ISSUE THREAD

**Issue by Shahar-Y** [TechnionYP5777/UpAndGo#340]
In the case when I create an event, and after that I build the automatic time table, it shows weired information: (user events -999999 instead of the event name)
![image](https://user-images.githubusercontent.com/23077804/27769015-7999fb84-5f29-11e7-8ff4-3bebb5df7b23.png)

log:
![image](https://user-images.githubusercontent.com/23077804/27769031-a646d7d8-5f29-11e7-8444-8ceb64273ca8.png)

**Comment by kobybs** [comment]
thanks, it's not much of a problem, we decided all user events will be under the same "Course" name, which is 999999, because if you have more than two events we can't tell which one of them if the one who cause the problem. but we probably should not present 99999 to the user. and translate 'user events' to hebrew and add some explanations. thanks.

**Comment by Shahar-Y** [comment]
Great! please update here when its done.
