### ISSUE TITLE
Equals Courses

### ISSUE THREAD

**Issue by SapirBismot** [TechnionYP5777/UpAndGo#68]
This came from a doubt in the prerequisites tree:
For example: the prerequisites of 234123 (Operation System) are: 234118 + 234218 (in the tree this will be 2 fathers)
but, the prerequisites of 234122 (Matam) are: 234114 or 234111 (this might be one father).

One solution that I thought about: every course points to an object that contains a list with all the courses that are equals to it.
The problem in this solution is how to maintain if and get the information:
https://ug3.technion.ac.il/rishum/course/234114
In the UG information of each course there's "מקצועות ללא זיכוי נוסף".
234127(Matlab) is "מקצוע ללא זיכוי נוסף" of 234114
but 234127(Matlab) is not a prerequisite of Matam.

Edit:
One more solution: instead each course will point to that object that I described, each catalog points to a list with all courses on it, and each course points to that object.
In this way, the catalog decides which courses are equals or not.

**Comment by SapirBismot** [comment]
@nikitadizhur @OmriBS @alexvitho @Lidkin5 @leyaniv @kobybs What do you think?
(Sorry for the English :dango: )

**Comment by nikitadizhur** [comment]
@SapirBismot instead of tree structure, why don't do it graph instead? I think it will solve most of the problems. Maximum, you can make more than one type of edge and vertex if you need.
Data in vertex can be simply a course name without actual pointer to course.
You can make, for example, three types of edges:
kdam, z'amud, lelo-zikui.
And than you can put some logic in Vertex to get needed heighbours and some logic in Scheduler to do appropriate search in graph.

**Comment by yossigil** [comment]
@nikitadizhur  is right.Use a graph, not a tree.
