### ISSUE TITLE
update Course to work with LessonGroup

### ISSUE THREAD

**Issue by kobybs** [TechnionYP5777/UpAndGo#73]
class Course need to have those variables
```
protected final List<LessonGroup> lectures;
protected final List<LessonGroup> tutorials;
```
and initialize them according to the parser data.
Course already has a Lessons list which nikita seems to initalize correctly, use it.

**Comment by kobybs** [comment]
needs to be done as soon as possible.

**Comment by OmriBS** [comment]
i've implemented LessonGroup class -
each group has group number (so we can distinguish between the seperate groups) and a list of lessons.
i can't initialize them according to the parser data yet because as far as i can see the xml db don't contains the data regarding the Lesson Groups so i don't have the db structure.
just assume that the class works and i will take care of the initialization.. so each course contains list of Lesson Groups and each element in this list contains a list of all lessons in the specific group.
tell me if there are things that needs a change

**Comment by kobybs** [comment]
@OmriBS not sure if this issue is still relevant, close it if its already done.
